# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Aurora<sup>64</sup>
email: contacto@auroraspace.cl
author: Aurora Space
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/auroraspaceproj
  - title: github
    url: https://github.com/auroraspace
  - title: linkedin
    url: https://www.linkedin.com/company/aurora-space
